'use strict'
// const { google } = require('googleapis')

// module.exports = async () => {
//   const auth = new google.auth.GoogleAuth({
//     keyFile: 'config/credentials.json',
//     scopes: 'https://www.googleapis.com/auth/spreadsheets'
//   })
//   return await auth.getClient()
// }
const scopes = require('../config/scopes')
const { GoogleSpreadsheet } = require('google-spreadsheet')
const { JWT } = require('google-auth-library')

// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: process.env.GS_CLIENT_EMAIL,
  key: process.env.GS_PRIVATE_KEY.replace(/\\n/g, '\n'),
  scopes: scopes
})

const Sheet = new GoogleSpreadsheet(process.env.PR_SPREADSHEET_ID, serviceAccountAuth)

module.exports = Sheet
